//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
  
    ViewBag.Title = "Hesap Özeti";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                     __o = Session["UserName"];


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                  __o = ViewBag.Rozet;


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                   __o = ViewBag.ToplamBagisTutari;


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                foreach (var bagis in ViewBag.SonBagislar)
                                {
                                    

#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                           __o = bagis.ProjeAd;


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                     __o = bagis.BagisTarihi.ToString("dd.MM.yyyy HH:mm:ss");


#line default
#line hidden

#line 8 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                                                                                  __o = bagis.BagisMiktari;


#line default
#line hidden

#line 9 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                         
                                }

#line default
#line hidden

#line 10 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                                                           __o = Session["UserPhone"];


#line default
#line hidden

#line 11 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                                                          __o = Session["UserEmail"];


#line default
#line hidden

#line 12 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                                                      __o = Session["UserIl"];


#line default
#line hidden

#line 13 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                                                        __o = Session["UserIlce"];


#line default
#line hidden

#line 14 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
             __o = Url.Action("GeriBildirim", "Account");


#line default
#line hidden

#line 15 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                 __o = Url.Action("GeriBildirimGonder", "Account");


#line default
#line hidden

#line 16 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                 __o = Url.Action("GuncelleIletisim", "Account")Url.Action("GeriBildirim", "Account");


17ine default
#line hidden

#line 15 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik                  \AccouUrl.Action("GuncelleSifre", "Account")nt\Index.cshtml"
             __o = Url.Act18n("GeriBildirimGonder", "Account");


#line default
#line hidden

#line 16 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C96         C\2\Ýyilik KöprüsüGeriBildirimGonderViews\Account\Index.cshtml"
                 __o = Url.A19ion("GuncelleIletisim", "Account");


#line default
#line hidden

#line 17 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C96          C\2\Ýyilik KöprüsüBagislarimsü\Views\Account\Index.cshtml"
                 __o = Ur20Action("GuncelleSifre", "Account");


#line default
#line hidden

#line 18 "C:\Users\rabia\AppData\Local\Temp\FF622A02C5C2596C966512FC2F33B4B8A74C\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
             __o = Url.Action("YorumYap", "Account");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
  
    ViewBag.Title = "Hesap Özeti";
    Layout = "~/Views/Shared/_Layout.cshtml";

    // Backend'den çekilecek veriler
    decimal toplamBagisTutari = 1250.50m; // Örnek toplam baðýþ
    var sonBagislar = new List<dynamic>
{
        new { ProjeAdi = "Eðitim Desteði", BagisTarihi = DateTime.Now.AddDays(-2), Tutar = 250.00m },
        new { ProjeAdi = "Saðlýk Projesi", BagisTarihi = DateTime.Now.AddDays(-10), Tutar = 500.00m },
        new { ProjeAdi = "Afet Yardýmý", BagisTarihi = DateTime.Now.AddDays(-20), Tutar = 500.50m }
    };


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                   __o = toplamBagisTutari;


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                foreach (var bagis in sonBagislar)
                                {
                                    

#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                           __o = bagis.ProjeAdi;


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                      __o = bagis.BagisTarihi.ToString("dd MMM yyyy");


#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                                                                                                           __o = bagis.Tutar;


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Account\Index.cshtml"
                                         
                                }

#line default
#line hidden
}
}
}
