//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                          __o = Url.Content("~/Content/favicon.ico");


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
           __o = Url.Content("~/Content/bootstrap.min.css");


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
           __o = Url.Content("~/Content/style.css");


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
            __o = Url.Content("~/Scripts/bootstrap.bundle.min.js");


#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("Index", "About");


#line default
#line hidden

#line 8 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                         __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 9 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                        __o = Url.Action("Index", "Donate");


#line default
#line hidden

#line 10 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                    if (Session["UserID"] != null)
                    {
                        

#line default
#line hidden

#line 11 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                           __o = Session["UserName"];


#line default
#line hidden

#line 12 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                              __o = Url.Action("Index", "Account");


#line default
#line hidden

#line 13 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                              __o = Url.Action("Logout", "Login");


#line default
#line hidden

#line 14 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                             
                    }
                    else
                    {
                        

#line default
#line hidden

#line 15 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                                     __o = Url.Action("Index", "Login");


#line default
#line hidden

#line 16 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                             
                    }

#line default
#line hidden

#line 17 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
           __o = Url.Content("~/Content/bootstrap.min.css");


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
           __o = Url.Content("~/Content/style.css");


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
            __o = Url.Content("~/Scripts/bootstrap.bundle.min.js");


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("About", "Home");


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                         __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 8 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                        __o = Url.Action("Index", "Donate");


#line default
#line hidden

#line 9 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                                 __o = Url.Action("Index", "Login");


#line default
#line hidden

#line 10 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                            __o = Url.Content("~/Content/style.css");


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("About", "Home");


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                         __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                     __o = Url.Action("Index", "Donate");


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                                 __o = Url.Action("Index", "Login");


#line default
#line hidden

#line 8 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                            __o = Url.Content("~/Content/style.css");


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("About", "Home");


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                         __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                    __o = Url.Action("Index", "Donate");


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                                 __o = Url.Action("Index", "Login");


#line default
#line hidden

#line 8 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                            __o = Url.Content("~/Content/style.css");


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("About", "Home");


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                         __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                    __o = Url.Action("Index", "Donate");


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                                 __o = Url.Action("Index", "Login");


#line default
#line hidden

#line 8 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                            __o = Url.Content("~/Content/style.css");


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("About", "Home");


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                         __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                    __o = Url.Action("Index", "Donate");


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
                                                                 __o = Url.Action("Login", "Account");


#line default
#line hidden

#line 8 "C:\Users\rabia\AppData\Local\Temp\BDEAA255F1610DAA1A98B43C721443F203EC\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
