//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
  
    ViewBag.Title = "Oturum Aç";


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                           __o = ViewBag.ActiveTab == "login" || ViewBag.ActiveTab == null ? "active" : "";


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                           __o = ViewBag.ActiveTab == "register" ? "active" : "";


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                              __o = ViewBag.ActiveTab == "login" || ViewBag.ActiveTab == null ? "show active" : "";


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                            if (ViewBag.ErrorMessage != null && ViewBag.ActiveTab == "login")
                            {
                                

#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                           __o = ViewBag.ErrorMessage;


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                                                           
                            }

#line default
#line hidden

#line 8 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                   __o = Url.Action("Login", "Login");


#line default
#line hidden

#line 9 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                              __o = ViewBag.ActiveTab == "register" ? "show active" : "";


#line default
#line hidden

#line 10 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                            if (ViewBag.ErrorMessage != null && ViewBag.ActiveTab == "register")
                            {
                                

#line default
#line hidden

#line 11 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                           __o = ViewBag.ErrorMessage;


#line default
#line hidden

#line 12 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                                                           
                            }

#line default
#line hidden

#line 13 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                   __o = Url.Action("Register", "Login");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
  
    ViewBag.Title = "Oturum Aç";


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                           __o = ViewBag.ActiveTab == "login" || ViewBag.ActiveTab == null ? "active" : "";


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                           __o = ViewBag.ActiveTab == "register" ? "active" : "";


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                              __o = ViewBag.ActiveTab == "login" || ViewBag.ActiveTab == null ? "show active" : "";


#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                            if (ViewBag.ErrorMessage != null && ViewBag.ActiveTab == "login")
                            {
                                

#line default
#line hidden

#line 6 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                           __o = ViewBag.ErrorMessage;


#line default
#line hidden

#line 7 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                                                           
                            }

#line default
#line hidden

#line 8 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                   __o = Url.Action("Login", "Login");


#line default
#line hidden

#line 9 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                              __o = ViewBag.ActiveTab == "register" ? "show active" : "";


#line default
#line hidden

#line 10 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                            if (ViewBag.ErrorMessage != null && ViewBag.ActiveTab == "register")
                            {
                                

#line default
#line hidden

#line 11 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                           __o = ViewBag.ErrorMessage;


#line default
#line hidden

#line 12 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                                                           
                            }

#line default
#line hidden

#line 13 "C:\Users\rabia\AppData\Local\Temp\617C7946E8B625091599CE236CD7AC3E200B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Login\Index.cshtml"
                                                   __o = Url.Action("Register", "Login");


#line default
#line hidden
}
}
}
