//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\AdminLogin\Index.cshtml"
  
    ViewBag.Title = "Yönetici Giriþi";


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\AdminLogin\Index.cshtml"
                    if (ViewBag.ErrorMessage != null)
                    {
                        

#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\AdminLogin\Index.cshtml"
                                                   __o = ViewBag.ErrorMessage;


#line default
#line hidden

#line 4 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\AdminLogin\Index.cshtml"
                                                                                   
                    }

#line default
#line hidden

#line 5 "C:\Users\rabia\AppData\Local\Temp\DF0D7B634427524B2C60533466466A7E262B\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\AdminLogin\Index.cshtml"
                                           __o = Url.Action("Login", "Admin");


#line default
#line hidden
efault
#line hidden
}
}
}
