//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
  
    ViewBag.Title = "Baðýþ Yap";


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
                       __o = Html.DropDownList("kategori_id", new List<SelectListItem> {
                                new SelectListItem { Text = "Kategori Seçiniz", Value = "", Selected = true },
                                new SelectListItem { Text = "Tümünü Göster", Value = "0" }
                            }.Concat((SelectList)ViewBag.Categories), new { @class = "form-control", id = "kategoriDropdown" });


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\2856978DEBD8B7459DBEF9F7EDDAEEC6B0BF\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
                       __o = Html.DropDownList("proje_id", new List<SelectListItem> {
                                new SelectListItem { Text = "Önce kategori seçiniz", Value = "", Selected = true }
                            }.Concat((SelectList)ViewBag.Projects), new { @class = "form-control", id = "projeDropdown" });


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
  
    ViewBag.Title = "Baðýþ Yap";


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
   __o = Html.DropDownList("kategori_id", (SelectList)ViewBag.Categories, "Kategori Seçiniz", new { @class = "form-control", id = "kategoriDropdown" });


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
   __o = Html.DropDownList("proje_id", (SelectList)ViewBag.Projects, "Önce kategori seçiniz", new { @class = "form-control", id = "projeDropdown" });


#line default
#line hidden
 "C:\Users\rabia\AppData\Local\Temp\59AA775DBC8DBF34961EBC7DD8370FE466B2\4\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
   __o = Html.DropDownList("proje_id", (SelectList)ViewBag.Projects, "Önce kategori seçiniz", new { @class = "form-control", id = "projeDropdown" });


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
  

#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
   __o = ;


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
   __o = ;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
  
    ViewBag.Title = "Baðýþ Yap";


#line default
#line hidden

#line 2 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
   __o = Html.DropDownList("kategori_id", (SelectList)ViewBag.Categories, "Kategori Seçiniz", new { @class = "form-control", id = "kategoriDropdown" });


#line default
#line hidden

#line 3 "C:\Users\rabia\AppData\Local\Temp\34DDD5F49D07DA3E0C657BA3E460F933132D\2\Ýyilik Köprüsü\Ýyilik Köprüsü\Views\Donate\Index.cshtml"
   __o = Html.DropDownList("proje_id", (SelectList)ViewBag.Projects, "Önce kategori seçiniz", new { @class = "form-control", id = "projeDropdown" });


#line default
#line hidden
}
}
}
