//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BagisDBEntities : DbContext
    {
        public BagisDBEntities()
            : base("name=BagisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bagis> Bagis { get; set; }
        public virtual DbSet<Gelir> Gelir { get; set; }
        public virtual DbSet<GeriBildirim> GeriBildirim { get; set; }
        public virtual DbSet<GeriBildirimTipi> GeriBildirimTipi { get; set; }
        public virtual DbSet<Gider> Gider { get; set; }
        public virtual DbSet<IslemTuru> IslemTuru { get; set; }
        public virtual DbSet<KullaniciAdresi> KullaniciAdresi { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Loglar> Loglar { get; set; }
        public virtual DbSet<OdemeYontemi> OdemeYontemi { get; set; }
        public virtual DbSet<Proje> Proje { get; set; }
        public virtual DbSet<ProjeKategori> ProjeKategori { get; set; }
        public virtual DbSet<ProjeYorumlari> ProjeYorumlari { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Rozetler> Rozetler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yedekler> Yedekler { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }
        public virtual DbSet<KullaniciLoginSorgu> KullaniciLoginSorgu { get; set; }
    
        public virtual int BagisYap(Nullable<int> kullanici_id, Nullable<int> odeme_yontem_id, Nullable<int> proje_id, Nullable<decimal> bagis_miktari, Nullable<System.DateTime> bagis_tarihi)
        {
            var kullanici_idParameter = kullanici_id.HasValue ?
                new ObjectParameter("kullanici_id", kullanici_id) :
                new ObjectParameter("kullanici_id", typeof(int));
    
            var odeme_yontem_idParameter = odeme_yontem_id.HasValue ?
                new ObjectParameter("odeme_yontem_id", odeme_yontem_id) :
                new ObjectParameter("odeme_yontem_id", typeof(int));
    
            var proje_idParameter = proje_id.HasValue ?
                new ObjectParameter("proje_id", proje_id) :
                new ObjectParameter("proje_id", typeof(int));
    
            var bagis_miktariParameter = bagis_miktari.HasValue ?
                new ObjectParameter("bagis_miktari", bagis_miktari) :
                new ObjectParameter("bagis_miktari", typeof(decimal));
    
            var bagis_tarihiParameter = bagis_tarihi.HasValue ?
                new ObjectParameter("bagis_tarihi", bagis_tarihi) :
                new ObjectParameter("bagis_tarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BagisYap", kullanici_idParameter, odeme_yontem_idParameter, proje_idParameter, bagis_miktariParameter, bagis_tarihiParameter);
        }
    
        public virtual int KullaniciVeVerileriniSil(Nullable<int> kullanici_id)
        {
            var kullanici_idParameter = kullanici_id.HasValue ?
                new ObjectParameter("kullanici_id", kullanici_id) :
                new ObjectParameter("kullanici_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KullaniciVeVerileriniSil", kullanici_idParameter);
        }
    
        public virtual int MisafirKullaniciEkle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MisafirKullaniciEkle");
        }
    
        public virtual int ProjeSil(Nullable<int> proje_id)
        {
            var proje_idParameter = proje_id.HasValue ?
                new ObjectParameter("proje_id", proje_id) :
                new ObjectParameter("proje_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProjeSil", proje_idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UyeEkle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UyeEkle");
        }
    
        public virtual int YedekAl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YedekAl");
        }
    }
}
