//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeriBildirim
    {
        public int geribildirim_id { get; set; }
        public int kullanici_id { get; set; }
        public int geribildirim_tipi_id { get; set; }
        public string geribildirim_mesaj { get; set; }
        public System.DateTime geribildirim_tarihi { get; set; }
    
        public virtual GeriBildirimTipi GeriBildirimTipi { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
