//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciLoginSorgu
    {
        public int kullanici_id { get; set; }
        public string e_mail { get; set; }
        public string telefon { get; set; }
        public string ad_soyad { get; set; }
        public string ilce_adi { get; set; }
        public string sehir_adi { get; set; }
        public string sifre { get; set; }
        public int rol_id { get; set; }
    }
}
