//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciAdresi
    {
        public int adres_id { get; set; }
        public int kullanici_id { get; set; }
        public string sehir_adi { get; set; }
        public string ilce_adi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
