//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Bagis = new HashSet<Bagis>();
            this.GeriBildirim = new HashSet<GeriBildirim>();
            this.KullaniciAdresi = new HashSet<KullaniciAdresi>();
            this.Loglar = new HashSet<Loglar>();
            this.ProjeYorumlari = new HashSet<ProjeYorumlari>();
        }
    
        public int kullanici_id { get; set; }
        public int rol_id { get; set; }
        public Nullable<int> rozet_id { get; set; }
        public string ad_soyad { get; set; }
        public string e_mail { get; set; }
        public string telefon { get; set; }
        public string sifre { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bagis> Bagis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeriBildirim> GeriBildirim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciAdresi> KullaniciAdresi { get; set; }
        public virtual Roller Roller { get; set; }
        public virtual Rozetler Rozetler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loglar> Loglar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjeYorumlari> ProjeYorumlari { get; set; }
    }
}
