//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int log_id { get; set; }
        public int kullanici_id { get; set; }
        public int islem_turu_id { get; set; }
        public System.DateTime islem_tarihi { get; set; }
    
        public virtual IslemTuru IslemTuru { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
