//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proje()
        {
            this.Bagis = new HashSet<Bagis>();
            this.ProjeYorumlari = new HashSet<ProjeYorumlari>();
        }
    
        public int proje_id { get; set; }
        public int kategori_id { get; set; }
        public string proje_ad { get; set; }
        public string proje_aciklamasi { get; set; }
        public string proje_resim_link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bagis> Bagis { get; set; }
        public virtual ProjeKategori ProjeKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjeYorumlari> ProjeYorumlari { get; set; }
    }
}
