//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeYorumlari
    {
        public int yorum_id { get; set; }
        public int proje_id { get; set; }
        public int kullanici_id { get; set; }
        public string yorum_metni { get; set; }
        public System.DateTime yorum_tarihi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Proje Proje { get; set; }
    }
}
