//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yedekler
    {
        public int YedekID { get; set; }
        public string VeritabanıAdı { get; set; }
        public string YedekYolu { get; set; }
        public Nullable<System.DateTime> YedeklemeTarihi { get; set; }
        public string Durum { get; set; }
    }
}
