//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İyilik_Köprüsü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetici
    {
        public int yonetici_id { get; set; }
        public string yonetici_ad_soyad { get; set; }
        public string yonetici_sifre { get; set; }
        public string yonetici_mail { get; set; }
        public string yonetici_telefon { get; set; }
    }
}
